package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AclClass generated by hbm2java
 */
public class AclClass  implements java.io.Serializable {


     private Short id;
     private String class_;
     private Set aclObjectIdentities = new HashSet(0);

    public AclClass() {
    }

	
    public AclClass(String class_) {
        this.class_ = class_;
    }
    public AclClass(String class_, Set aclObjectIdentities) {
       this.class_ = class_;
       this.aclObjectIdentities = aclObjectIdentities;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public Set getAclObjectIdentities() {
        return this.aclObjectIdentities;
    }
    
    public void setAclObjectIdentities(Set aclObjectIdentities) {
        this.aclObjectIdentities = aclObjectIdentities;
    }




}


