package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA



/**
 * AclEntry generated by hbm2java
 */
public class AclEntry  implements java.io.Serializable {


     private Integer id;
     private AclObjectIdentity aclObjectIdentity;
     private AclSid aclSid;
     private int aceOrder;
     private int mask;
     private boolean granting;
     private boolean auditSuccess;
     private boolean auditFailure;

    public AclEntry() {
    }

    public AclEntry(AclObjectIdentity aclObjectIdentity, AclSid aclSid, int aceOrder, int mask, boolean granting, boolean auditSuccess, boolean auditFailure) {
       this.aclObjectIdentity = aclObjectIdentity;
       this.aclSid = aclSid;
       this.aceOrder = aceOrder;
       this.mask = mask;
       this.granting = granting;
       this.auditSuccess = auditSuccess;
       this.auditFailure = auditFailure;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AclObjectIdentity getAclObjectIdentity() {
        return this.aclObjectIdentity;
    }
    
    public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
        this.aclObjectIdentity = aclObjectIdentity;
    }
    public AclSid getAclSid() {
        return this.aclSid;
    }
    
    public void setAclSid(AclSid aclSid) {
        this.aclSid = aclSid;
    }
    public int getAceOrder() {
        return this.aceOrder;
    }
    
    public void setAceOrder(int aceOrder) {
        this.aceOrder = aceOrder;
    }
    public int getMask() {
        return this.mask;
    }
    
    public void setMask(int mask) {
        this.mask = mask;
    }
    public boolean isGranting() {
        return this.granting;
    }
    
    public void setGranting(boolean granting) {
        this.granting = granting;
    }
    public boolean isAuditSuccess() {
        return this.auditSuccess;
    }
    
    public void setAuditSuccess(boolean auditSuccess) {
        this.auditSuccess = auditSuccess;
    }
    public boolean isAuditFailure() {
        return this.auditFailure;
    }
    
    public void setAuditFailure(boolean auditFailure) {
        this.auditFailure = auditFailure;
    }




}


