package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AclObjectIdentity generated by hbm2java
 */
public class AclObjectIdentity  implements java.io.Serializable {


     private Integer id;
     private AclSid aclSid;
     private AclObjectIdentity aclObjectIdentity;
     private AclClass aclClass;
     private int objectIdIdentity;
     private boolean entriesInheriting;
     private Set aclObjectIdentities = new HashSet(0);
     private Set aclEntries = new HashSet(0);

    public AclObjectIdentity() {
    }

	
    public AclObjectIdentity(AclClass aclClass, int objectIdIdentity, boolean entriesInheriting) {
        this.aclClass = aclClass;
        this.objectIdIdentity = objectIdIdentity;
        this.entriesInheriting = entriesInheriting;
    }
    public AclObjectIdentity(AclSid aclSid, AclObjectIdentity aclObjectIdentity, AclClass aclClass, int objectIdIdentity, boolean entriesInheriting, Set aclObjectIdentities, Set aclEntries) {
       this.aclSid = aclSid;
       this.aclObjectIdentity = aclObjectIdentity;
       this.aclClass = aclClass;
       this.objectIdIdentity = objectIdIdentity;
       this.entriesInheriting = entriesInheriting;
       this.aclObjectIdentities = aclObjectIdentities;
       this.aclEntries = aclEntries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AclSid getAclSid() {
        return this.aclSid;
    }
    
    public void setAclSid(AclSid aclSid) {
        this.aclSid = aclSid;
    }
    public AclObjectIdentity getAclObjectIdentity() {
        return this.aclObjectIdentity;
    }
    
    public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
        this.aclObjectIdentity = aclObjectIdentity;
    }
    public AclClass getAclClass() {
        return this.aclClass;
    }
    
    public void setAclClass(AclClass aclClass) {
        this.aclClass = aclClass;
    }
    public int getObjectIdIdentity() {
        return this.objectIdIdentity;
    }
    
    public void setObjectIdIdentity(int objectIdIdentity) {
        this.objectIdIdentity = objectIdIdentity;
    }
    public boolean isEntriesInheriting() {
        return this.entriesInheriting;
    }
    
    public void setEntriesInheriting(boolean entriesInheriting) {
        this.entriesInheriting = entriesInheriting;
    }
    public Set getAclObjectIdentities() {
        return this.aclObjectIdentities;
    }
    
    public void setAclObjectIdentities(Set aclObjectIdentities) {
        this.aclObjectIdentities = aclObjectIdentities;
    }
    public Set getAclEntries() {
        return this.aclEntries;
    }
    
    public void setAclEntries(Set aclEntries) {
        this.aclEntries = aclEntries;
    }




}


