package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AclSid generated by hbm2java
 */
public class AclSid  implements java.io.Serializable {


     private Integer id;
     private Roles roles;
     private UserAccess userAccess;
     private boolean principal;
     private Set aclObjectIdentities = new HashSet(0);
     private Set aclEntries = new HashSet(0);

    public AclSid() {
    }

	
    public AclSid(Roles roles, UserAccess userAccess, boolean principal) {
        this.roles = roles;
        this.userAccess = userAccess;
        this.principal = principal;
    }
    public AclSid(Roles roles, UserAccess userAccess, boolean principal, Set aclObjectIdentities, Set aclEntries) {
       this.roles = roles;
       this.userAccess = userAccess;
       this.principal = principal;
       this.aclObjectIdentities = aclObjectIdentities;
       this.aclEntries = aclEntries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public UserAccess getUserAccess() {
        return this.userAccess;
    }
    
    public void setUserAccess(UserAccess userAccess) {
        this.userAccess = userAccess;
    }
    public boolean isPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(boolean principal) {
        this.principal = principal;
    }
    public Set getAclObjectIdentities() {
        return this.aclObjectIdentities;
    }
    
    public void setAclObjectIdentities(Set aclObjectIdentities) {
        this.aclObjectIdentities = aclObjectIdentities;
    }
    public Set getAclEntries() {
        return this.aclEntries;
    }
    
    public void setAclEntries(Set aclEntries) {
        this.aclEntries = aclEntries;
    }




}


