package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AddressMaster generated by hbm2java
 */
public class AddressMaster  implements java.io.Serializable {


     private String id;
     private UserAccess userAccessByCreatedBy;
     private UserAccess userAccessByModifiedBy;
     private String homeAddress1;
     private String homeAddress2;
     private String homeCity;
     private String homeState;
     private String homePinCode;
     private String homeCountry;
     private String officeAddress1;
     private String officeAddress2;
     private String officeCity;
     private String officeState;
     private String officePinCode;
     private String officeCountry;
     private Date creationDate=new java.util.Date();
     private Date modifiedDate;
     private String dataSource;
     private String entityStatus="ACTIVE";
     private String entityType;
     private Set userMasters = new HashSet(0);

    public AddressMaster() {
    }

	
    public AddressMaster(String id, String homeAddress1, String homeCity, String homeState, String homePinCode, String homeCountry, String dataSource, String entityStatus, String entityType) {
        this.id = id;
        this.homeAddress1 = homeAddress1;
        this.homeCity = homeCity;
        this.homeState = homeState;
        this.homePinCode = homePinCode;
        this.homeCountry = homeCountry;
        this.dataSource = dataSource;
        this.entityStatus = entityStatus;
        this.entityType = entityType;
    }
    public AddressMaster(String id, UserAccess userAccessByCreatedBy, UserAccess userAccessByModifiedBy, String homeAddress1, String homeAddress2, String homeCity, String homeState, String homePinCode, String homeCountry, String officeAddress1, String officeAddress2, String officeCity, String officeState, String officePinCode, String officeCountry, Date creationDate, Date modifiedDate, String dataSource, String entityStatus, String entityType, Set userMasters) {
       this.id = id;
       this.userAccessByCreatedBy = userAccessByCreatedBy;
       this.userAccessByModifiedBy = userAccessByModifiedBy;
       this.homeAddress1 = homeAddress1;
       this.homeAddress2 = homeAddress2;
       this.homeCity = homeCity;
       this.homeState = homeState;
       this.homePinCode = homePinCode;
       this.homeCountry = homeCountry;
       this.officeAddress1 = officeAddress1;
       this.officeAddress2 = officeAddress2;
       this.officeCity = officeCity;
       this.officeState = officeState;
       this.officePinCode = officePinCode;
       this.officeCountry = officeCountry;
       this.creationDate = creationDate;
       this.modifiedDate = modifiedDate;
       this.dataSource = dataSource;
       this.entityStatus = entityStatus;
       this.entityType = entityType;
       this.userMasters = userMasters;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public UserAccess getUserAccessByCreatedBy() {
        return this.userAccessByCreatedBy;
    }
    
    public void setUserAccessByCreatedBy(UserAccess userAccessByCreatedBy) {
        this.userAccessByCreatedBy = userAccessByCreatedBy;
    }
    public UserAccess getUserAccessByModifiedBy() {
        return this.userAccessByModifiedBy;
    }
    
    public void setUserAccessByModifiedBy(UserAccess userAccessByModifiedBy) {
        this.userAccessByModifiedBy = userAccessByModifiedBy;
    }
    public String getHomeAddress1() {
        return this.homeAddress1;
    }
    
    public void setHomeAddress1(String homeAddress1) {
        this.homeAddress1 = homeAddress1;
    }
    public String getHomeAddress2() {
        return this.homeAddress2;
    }
    
    public void setHomeAddress2(String homeAddress2) {
        this.homeAddress2 = homeAddress2;
    }
    public String getHomeCity() {
        return this.homeCity;
    }
    
    public void setHomeCity(String homeCity) {
        this.homeCity = homeCity;
    }
    public String getHomeState() {
        return this.homeState;
    }
    
    public void setHomeState(String homeState) {
        this.homeState = homeState;
    }
    public String getHomePinCode() {
        return this.homePinCode;
    }
    
    public void setHomePinCode(String homePinCode) {
        this.homePinCode = homePinCode;
    }
    public String getHomeCountry() {
        return this.homeCountry;
    }
    
    public void setHomeCountry(String homeCountry) {
        this.homeCountry = homeCountry;
    }
    public String getOfficeAddress1() {
        return this.officeAddress1;
    }
    
    public void setOfficeAddress1(String officeAddress1) {
        this.officeAddress1 = officeAddress1;
    }
    public String getOfficeAddress2() {
        return this.officeAddress2;
    }
    
    public void setOfficeAddress2(String officeAddress2) {
        this.officeAddress2 = officeAddress2;
    }
    public String getOfficeCity() {
        return this.officeCity;
    }
    
    public void setOfficeCity(String officeCity) {
        this.officeCity = officeCity;
    }
    public String getOfficeState() {
        return this.officeState;
    }
    
    public void setOfficeState(String officeState) {
        this.officeState = officeState;
    }
    public String getOfficePinCode() {
        return this.officePinCode;
    }
    
    public void setOfficePinCode(String officePinCode) {
        this.officePinCode = officePinCode;
    }
    public String getOfficeCountry() {
        return this.officeCountry;
    }
    
    public void setOfficeCountry(String officeCountry) {
        this.officeCountry = officeCountry;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }
    public Set getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set userMasters) {
        this.userMasters = userMasters;
    }




}


