package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContactMaster generated by hbm2java
 */
public class ContactMaster  implements java.io.Serializable {


     private String id;
     private UserAccess userAccessByCreatedBy;
     private UserAccess userAccessByModifiedBy;
     private String email;
     private String homePhone;
     private String officePhone;
     private String mobileNo;
     private String emergencyContactNo;
     private String relationWithContactPerson;
     private Date creationDate;
     private Date modifiedDate;
     private String dataSource;
     private String entityStatus;
     private String entityType;
     private Set userMasters = new HashSet(0);

    public ContactMaster() {
    }

	
    public ContactMaster(String id, String emergencyContactNo, String relationWithContactPerson, String dataSource, String entityStatus, String entityType) {
        this.id = id;
        this.emergencyContactNo = emergencyContactNo;
        this.relationWithContactPerson = relationWithContactPerson;
        this.dataSource = dataSource;
        this.entityStatus = entityStatus;
        this.entityType = entityType;
    }
    public ContactMaster(String id, UserAccess userAccessByCreatedBy, UserAccess userAccessByModifiedBy, String email, String homePhone, String officePhone, String mobileNo, String emergencyContactNo, String relationWithContactPerson, Date creationDate, Date modifiedDate, String dataSource, String entityStatus, String entityType, Set userMasters) {
       this.id = id;
       this.userAccessByCreatedBy = userAccessByCreatedBy;
       this.userAccessByModifiedBy = userAccessByModifiedBy;
       this.email = email;
       this.homePhone = homePhone;
       this.officePhone = officePhone;
       this.mobileNo = mobileNo;
       this.emergencyContactNo = emergencyContactNo;
       this.relationWithContactPerson = relationWithContactPerson;
       this.creationDate = creationDate;
       this.modifiedDate = modifiedDate;
       this.dataSource = dataSource;
       this.entityStatus = entityStatus;
       this.entityType = entityType;
       this.userMasters = userMasters;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public UserAccess getUserAccessByCreatedBy() {
        return this.userAccessByCreatedBy;
    }
    
    public void setUserAccessByCreatedBy(UserAccess userAccessByCreatedBy) {
        this.userAccessByCreatedBy = userAccessByCreatedBy;
    }
    public UserAccess getUserAccessByModifiedBy() {
        return this.userAccessByModifiedBy;
    }
    
    public void setUserAccessByModifiedBy(UserAccess userAccessByModifiedBy) {
        this.userAccessByModifiedBy = userAccessByModifiedBy;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getOfficePhone() {
        return this.officePhone;
    }
    
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getEmergencyContactNo() {
        return this.emergencyContactNo;
    }
    
    public void setEmergencyContactNo(String emergencyContactNo) {
        this.emergencyContactNo = emergencyContactNo;
    }
    public String getRelationWithContactPerson() {
        return this.relationWithContactPerson;
    }
    
    public void setRelationWithContactPerson(String relationWithContactPerson) {
        this.relationWithContactPerson = relationWithContactPerson;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }
    public Set getUserMasters() {
        return this.userMasters;
    }
    
    public void setUserMasters(Set userMasters) {
        this.userMasters = userMasters;
    }




}


