package com.prag.hms.hibernate.pojo;
// Generated 9 Jun, 2014 10:40:03 AM by Hibernate Tools 3.2.1.GA


/**
 * CountryMaster generated by hbm2java
 */
public class CountryMaster implements java.io.Serializable {

    private String countryName;
  
  
    public CountryMaster() {
    }

    public CountryMaster(String countryName) {
        this.countryName = countryName;
    }

    public String getCountryName() {
        return this.countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
}
