package com.prag.hms.hibernate.pojo;
// Generated 7 Jun, 2014 10:43:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HospitalMaster generated by hbm2java
 */
public class HospitalMaster  implements java.io.Serializable {


     private String hospitalId;
     private ContactMaster contactMaster;
     private AddressMaster addressMaster;
     private String hospitalName;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String dataSource;
     private String entityStatus;
     private Set hospitalNumbersMasters = new HashSet(0);

    public HospitalMaster() {
    }

	
    public HospitalMaster(String hospitalId) {
        this.hospitalId = hospitalId;
    }
    public HospitalMaster(String hospitalId, ContactMaster contactMaster, AddressMaster addressMaster, String hospitalName, String createdBy, Date creationDate, String modifiedBy, Date modifiedDate, String dataSource, String entityStatus, Set hospitalNumbersMasters) {
       this.hospitalId = hospitalId;
       this.contactMaster = contactMaster;
       this.addressMaster = addressMaster;
       this.hospitalName = hospitalName;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.dataSource = dataSource;
       this.entityStatus = entityStatus;
       this.hospitalNumbersMasters = hospitalNumbersMasters;
    }
   
    public String getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }
    public ContactMaster getContactMaster() {
        return this.contactMaster;
    }
    
    public void setContactMaster(ContactMaster contactMaster) {
        this.contactMaster = contactMaster;
    }
    public AddressMaster getAddressMaster() {
        return this.addressMaster;
    }
    
    public void setAddressMaster(AddressMaster addressMaster) {
        this.addressMaster = addressMaster;
    }
    public String getHospitalName() {
        return this.hospitalName;
    }
    
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public Set getHospitalNumbersMasters() {
        return this.hospitalNumbersMasters;
    }
    
    public void setHospitalNumbersMasters(Set hospitalNumbersMasters) {
        this.hospitalNumbersMasters = hospitalNumbersMasters;
    }




}


