package com.prag.hms.hibernate.pojo;
// Generated 7 Jun, 2014 10:43:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HospitalNumbersMaster generated by hbm2java
 */
public class HospitalNumbersMaster  implements java.io.Serializable {


     private HospitalNumbersMasterId id;
     private HospitalMaster hospitalMaster;
     private String hospitalPatientId;
     private Date hospitalRegistrationDate;
     private String dataSource;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String entityStatus;

    public HospitalNumbersMaster() {
    }

	
    public HospitalNumbersMaster(HospitalNumbersMasterId id, HospitalMaster hospitalMaster, String hospitalPatientId, Date hosptalRegistrationDate, String dataSource, String createdBy, Date creationDate, String entityStatus) {
        this.id = id;
        this.hospitalMaster = hospitalMaster;
        this.hospitalPatientId = hospitalPatientId;
        this.hospitalRegistrationDate = hosptalRegistrationDate;
        this.dataSource = dataSource;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.entityStatus = entityStatus;
    }
    public HospitalNumbersMaster(HospitalNumbersMasterId id, HospitalMaster hospitalMaster, String hospitalPatientId, Date hosptalRegistrationDate, String dataSource, String createdBy, Date creationDate, String modifiedBy, Date modifiedDate, String entityStatus) {
       this.id = id;
       this.hospitalMaster = hospitalMaster;
       this.hospitalPatientId = hospitalPatientId;
       this.hospitalRegistrationDate = hosptalRegistrationDate;
       this.dataSource = dataSource;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.entityStatus = entityStatus;
    }
   
    public HospitalNumbersMasterId getId() {
        return this.id;
    }
    
    public void setId(HospitalNumbersMasterId id) {
        this.id = id;
    }
    public HospitalMaster getHospitalMaster() {
        return this.hospitalMaster;
    }
    
    public void setHospitalMaster(HospitalMaster hospitalMaster) {
        this.hospitalMaster = hospitalMaster;
    }
    public String getHospitalPatientId() {
        return this.hospitalPatientId;
    }
    
    public void setHospitalPatientId(String hospitalPatientId) {
        this.hospitalPatientId = hospitalPatientId;
    }
    public Date getHospitalRegistrationDate() {
        return this.hospitalRegistrationDate;
    }
    
    public void setHospitalRegistrationDate(Date hospitalRegistrationDate) {
        this.hospitalRegistrationDate = hospitalRegistrationDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }




}


