package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private String roleId;
     private UserAccess userAccess;
     private String name;
     private String dataSource;
     private String entityStatus;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private Set userAccesses = new HashSet(0);
     private Set actionTypeses = new HashSet(0);
     private Set aclSids = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String roleId) {
        this.roleId = roleId;
    }
    public Roles(String roleId, UserAccess userAccess, String name, String dataSource, String entityStatus, Date creationDate, String modifiedBy, Date modifiedDate, Set userAccesses, Set actionTypeses, Set aclSids) {
       this.roleId = roleId;
       this.userAccess = userAccess;
       this.name = name;
       this.dataSource = dataSource;
       this.entityStatus = entityStatus;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.userAccesses = userAccesses;
       this.actionTypeses = actionTypeses;
       this.aclSids = aclSids;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public UserAccess getUserAccess() {
        return this.userAccess;
    }
    
    public void setUserAccess(UserAccess userAccess) {
        this.userAccess = userAccess;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getUserAccesses() {
        return this.userAccesses;
    }
    
    public void setUserAccesses(Set userAccesses) {
        this.userAccesses = userAccesses;
    }
    public Set getActionTypeses() {
        return this.actionTypeses;
    }
    
    public void setActionTypeses(Set actionTypeses) {
        this.actionTypeses = actionTypeses;
    }
    public Set getAclSids() {
        return this.aclSids;
    }
    
    public void setAclSids(Set aclSids) {
        this.aclSids = aclSids;
    }




}


