package com.prag.hms.hibernate.pojo;
// Generated 22 Apr, 2014 5:49:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private String roleId;
     private String name;
     private String dataSource;
     private String entityStatus;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private Set userAccesses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String roleId) {
        this.roleId = roleId;
    }
    public Roles(String roleId, String name, String dataSource, String entityStatus, String createdBy, Date creationDate, String modifiedBy, Date modifiedDate, Set userAccesses) {
       this.roleId = roleId;
       this.name = name;
       this.dataSource = dataSource;
       this.entityStatus = entityStatus;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.userAccesses = userAccesses;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getUserAccesses() {
        return this.userAccesses;
    }
    
    public void setUserAccesses(Set userAccesses) {
        this.userAccesses = userAccesses;
    }




}


