package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SecurityQuestionMaster generated by hbm2java
 */
public class SecurityQuestionMaster  implements java.io.Serializable {


     private String questionId;
     private UserAccess userAccessByCreatedBy;
     private UserAccess userAccessByModifiedBy;
     private String question;
     private String entityStatus;
     private Date creationDate;
     private Date modifiedDate;
     private String dataSource;
     private Set questionUserMaps = new HashSet(0);

    public SecurityQuestionMaster() {
    }

	
    public SecurityQuestionMaster(String questionId, String question, String entityStatus, String dataSource) {
        this.questionId = questionId;
        this.question = question;
        this.entityStatus = entityStatus;
        this.dataSource = dataSource;
    }
    public SecurityQuestionMaster(String questionId, UserAccess userAccessByCreatedBy, UserAccess userAccessByModifiedBy, String question, String entityStatus, Date creationDate, Date modifiedDate, String dataSource, Set questionUserMaps) {
       this.questionId = questionId;
       this.userAccessByCreatedBy = userAccessByCreatedBy;
       this.userAccessByModifiedBy = userAccessByModifiedBy;
       this.question = question;
       this.entityStatus = entityStatus;
       this.creationDate = creationDate;
       this.modifiedDate = modifiedDate;
       this.dataSource = dataSource;
       this.questionUserMaps = questionUserMaps;
    }
   
    public String getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }
    public UserAccess getUserAccessByCreatedBy() {
        return this.userAccessByCreatedBy;
    }
    
    public void setUserAccessByCreatedBy(UserAccess userAccessByCreatedBy) {
        this.userAccessByCreatedBy = userAccessByCreatedBy;
    }
    public UserAccess getUserAccessByModifiedBy() {
        return this.userAccessByModifiedBy;
    }
    
    public void setUserAccessByModifiedBy(UserAccess userAccessByModifiedBy) {
        this.userAccessByModifiedBy = userAccessByModifiedBy;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public Set getQuestionUserMaps() {
        return this.questionUserMaps;
    }
    
    public void setQuestionUserMaps(Set questionUserMaps) {
        this.questionUserMaps = questionUserMaps;
    }




}


