package com.prag.hms.hibernate.pojo;
// Generated 28 May, 2014 6:57:44 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * StagingPatientDoctorRecord generated by hbm2java
 */
public class StagingPatientDoctorRecord implements java.io.Serializable {

    private String stagingDoctorId;
    private StagingPatientHospitalRecord stagingPatientHospitalRecord;
    private String patientExchangeId;
    private String doctorsFirstName;
    private String doctorsLastName;
    private String specialization;
    private String doctorsEmail;
    private String officePhone;
    private String createdBy;
    private Date createdDate;
    private String modifiedBy;
    private Date modifiedDate;
    private String dataSource;

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getModifiedBy() {
        return modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Date getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public String getDataSource() {
        return dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    public StagingPatientDoctorRecord() {
    }

    public StagingPatientDoctorRecord(String stagingDoctorId) {
        this.stagingDoctorId = stagingDoctorId;
    }

    public StagingPatientDoctorRecord(String stagingDoctorId, StagingPatientHospitalRecord stagingPatientHospitalRecord, String patientExchangeId, String doctorsFirstName, String doctorsLastName, String specialization, String doctorsEmail, String officePhone) {
        this.stagingDoctorId = stagingDoctorId;
        this.stagingPatientHospitalRecord = stagingPatientHospitalRecord;
        this.patientExchangeId = patientExchangeId;
        this.doctorsFirstName = doctorsFirstName;
        this.doctorsLastName = doctorsLastName;
        this.specialization = specialization;
        this.doctorsEmail = doctorsEmail;
        this.officePhone = officePhone;
    }

    public String getStagingDoctorId() {
        return this.stagingDoctorId;
    }

    public void setStagingDoctorId(String stagingDoctorId) {
        this.stagingDoctorId = stagingDoctorId;
    }

    public StagingPatientHospitalRecord getStagingPatientHospitalRecord() {
        return this.stagingPatientHospitalRecord;
    }

    public void setStagingPatientHospitalRecord(StagingPatientHospitalRecord stagingPatientHospitalRecord) {
        this.stagingPatientHospitalRecord = stagingPatientHospitalRecord;
    }

    public String getPatientExchangeId() {
        return this.patientExchangeId;
    }

    public void setPatientExchangeId(String patientExchangeId) {
        this.patientExchangeId = patientExchangeId;
    }

    public String getDoctorsFirstName() {
        return this.doctorsFirstName;
    }

    public void setDoctorsFirstName(String doctorsFirstName) {
        this.doctorsFirstName = doctorsFirstName;
    }

    public String getDoctorsLastName() {
        return this.doctorsLastName;
    }

    public void setDoctorsLastName(String doctorsLastName) {
        this.doctorsLastName = doctorsLastName;
    }

    public String getSpecialization() {
        return this.specialization;
    }

    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }

    public String getDoctorsEmail() {
        return this.doctorsEmail;
    }

    public void setDoctorsEmail(String doctorsEmail) {
        this.doctorsEmail = doctorsEmail;
    }

    public String getOfficePhone() {
        return this.officePhone;
    }

    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone;
    }
}
