package com.prag.hms.hibernate.pojo;
// Generated 22 Apr, 2014 5:49:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserMaster generated by hbm2java
 */
public class UserMaster  implements java.io.Serializable {


     private String userId;
     private ContactMaster contactMaster;
     private AddressMaster addressMaster;
     private String entityStatus;
     private String firstName;
     private String middleName;
     private String lastName;
     private Date dob;
     private char gender;
     private String bloodGroup;
     private String fatherFirstName;
     private String fatherLastName;
     private String motherFirstName;
     private String motherLastName;
     private String firstLanguage;
     private String secondLanguage;
     private String thirdLanguage;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String dataSource;

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public char getGender() {
        return gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public String getBloodGroup() {
        return bloodGroup;
    }

    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }
     private String nationality;
     private String hospitalId;
     private Set userAccessesForModifiedBy = new HashSet(0);
     private Set userAccessesForCreatedBy = new HashSet(0);
     private Set userAccessesForUserId = new HashSet(0);

    public UserMaster() {
    }

	
    public UserMaster(String userId) {
        this.userId = userId;
    }
    public UserMaster(String userId, ContactMaster contactMaster, AddressMaster addressMaster, String entityStatus, String firstName, String lastName, Date dob, String fatherFirstName, String fatherLastName, String motherFirstName, String motherLastName, String firstLanguage, String secondLanguage, String thirdLanguage, String createdBy, Date creationDate, String modifiedBy, Date modifiedDate, String dataSource, String nationality, String hospitalId, Set userAccessesForModifiedBy, Set userAccessesForCreatedBy, Set userAccessesForUserId) {
       this.userId = userId;
       this.contactMaster = contactMaster;
       this.addressMaster = addressMaster;
       this.entityStatus = entityStatus;
       this.firstName = firstName;
       this.lastName = lastName;
       this.dob = dob;
       this.fatherFirstName = fatherFirstName;
       this.fatherLastName = fatherLastName;
       this.motherFirstName = motherFirstName;
       this.motherLastName = motherLastName;
       this.firstLanguage = firstLanguage;
       this.secondLanguage = secondLanguage;
       this.thirdLanguage = thirdLanguage;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.dataSource = dataSource;
       this.nationality = nationality;
       this.hospitalId = hospitalId;
       this.userAccessesForModifiedBy = userAccessesForModifiedBy;
       this.userAccessesForCreatedBy = userAccessesForCreatedBy;
       this.userAccessesForUserId = userAccessesForUserId;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public ContactMaster getContactMaster() {
        return this.contactMaster;
    }
    
    public void setContactMaster(ContactMaster contactMaster) {
        this.contactMaster = contactMaster;
    }
    public AddressMaster getAddressMaster() {
        return this.addressMaster;
    }
    
    public void setAddressMaster(AddressMaster addressMaster) {
        this.addressMaster = addressMaster;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getFatherFirstName() {
        return this.fatherFirstName;
    }
    
    public void setFatherFirstName(String fatherFirstName) {
        this.fatherFirstName = fatherFirstName;
    }
    public String getFatherLastName() {
        return this.fatherLastName;
    }
    
    public void setFatherLastName(String fatherLastName) {
        this.fatherLastName = fatherLastName;
    }
    public String getMotherFirstName() {
        return this.motherFirstName;
    }
    
    public void setMotherFirstName(String motherFirstName) {
        this.motherFirstName = motherFirstName;
    }
    public String getMotherLastName() {
        return this.motherLastName;
    }
    
    public void setMotherLastName(String motherLastName) {
        this.motherLastName = motherLastName;
    }
    public String getFirstLanguage() {
        return this.firstLanguage;
    }
    
    public void setFirstLanguage(String firstLanguage) {
        this.firstLanguage = firstLanguage;
    }
    public String getSecondLanguage() {
        return this.secondLanguage;
    }
    
    public void setSecondLanguage(String secondLanguage) {
        this.secondLanguage = secondLanguage;
    }
    public String getThirdLanguage() {
        return this.thirdLanguage;
    }
    
    public void setThirdLanguage(String thirdLanguage) {
        this.thirdLanguage = thirdLanguage;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }
    public Set getUserAccessesForModifiedBy() {
        return this.userAccessesForModifiedBy;
    }
    
    public void setUserAccessesForModifiedBy(Set userAccessesForModifiedBy) {
        this.userAccessesForModifiedBy = userAccessesForModifiedBy;
    }
    public Set getUserAccessesForCreatedBy() {
        return this.userAccessesForCreatedBy;
    }
    
    public void setUserAccessesForCreatedBy(Set userAccessesForCreatedBy) {
        this.userAccessesForCreatedBy = userAccessesForCreatedBy;
    }
    public Set getUserAccessesForUserId() {
        return this.userAccessesForUserId;
    }
    
    public void setUserAccessesForUserId(Set userAccessesForUserId) {
        this.userAccessesForUserId = userAccessesForUserId;
    }




}


