package com.prag.hms.hibernate.pojo;
// Generated 22 Apr, 2014 5:49:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAccess generated by hbm2java
 */
public class UserAccess  implements java.io.Serializable {


     private String loginName;
     private UserMaster userMasterByCreatedBy;
     private UserMaster userMasterByUserId;
     private UserMaster userMasterByModifiedBy;
     private String entityStatus;
     private String password;
     private Date passwordExpDate;
     private String dataSource;
     private String designation;
     private String managerId;
     private String deptId;
     private String hospitalId;
     private Date creationDate;
     private Date modifiedDate;
     private Set<Roles> roleses = new HashSet<Roles>(0);

    public UserAccess() {
    }

	
    public UserAccess(String loginName, UserMaster userMasterByUserId) {
        this.loginName = loginName;
        this.userMasterByUserId = userMasterByUserId;
    }
    public UserAccess(String loginName, UserMaster userMasterByCreatedBy, UserMaster userMasterByUserId, UserMaster userMasterByModifiedBy, String entityStatus, String password, Date passwordExpDate, String dataSource, String designation, String managerId, String deptId, String hospitalId, Date creationDate, Date modifiedDate, Set<Roles> roleses) {
       this.loginName = loginName;
       this.userMasterByCreatedBy = userMasterByCreatedBy;
       this.userMasterByUserId = userMasterByUserId;
       this.userMasterByModifiedBy = userMasterByModifiedBy;
       this.entityStatus = entityStatus;
       this.password = password;
       this.passwordExpDate = passwordExpDate;
       this.dataSource = dataSource;
       this.designation = designation;
       this.managerId = managerId;
       this.deptId = deptId;
       this.hospitalId = hospitalId;
       this.creationDate = creationDate;
       this.modifiedDate = modifiedDate;
       this.roleses = roleses;
    }
   
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public UserMaster getUserMasterByCreatedBy() {
        return this.userMasterByCreatedBy;
    }
    
    public void setUserMasterByCreatedBy(UserMaster userMasterByCreatedBy) {
        this.userMasterByCreatedBy = userMasterByCreatedBy;
    }
    public UserMaster getUserMasterByUserId() {
        return this.userMasterByUserId;
    }
    
    public void setUserMasterByUserId(UserMaster userMasterByUserId) {
        this.userMasterByUserId = userMasterByUserId;
    }
    public UserMaster getUserMasterByModifiedBy() {
        return this.userMasterByModifiedBy;
    }
    
    public void setUserMasterByModifiedBy(UserMaster userMasterByModifiedBy) {
        this.userMasterByModifiedBy = userMasterByModifiedBy;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getPasswordExpDate() {
        return this.passwordExpDate;
    }
    
    public void setPasswordExpDate(Date passwordExpDate) {
        this.passwordExpDate = passwordExpDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }
    public String getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }




}


