package com.prag.hms.hibernate.pojo;
// Generated 1 May, 2014 5:57:32 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserMaster generated by hbm2java
 */
public class UserMaster  implements java.io.Serializable {


     private String userId;
     private UserAccess userAccessByCreatedBy;
     private ContactMaster contactMaster;
     private UserAccess userAccessByModifiedBy;
     private AddressMaster addressMaster;
     private String entityStatus="ACTIVE";
     private String firstName;
     private String middleName;
     private String lastName;
     private String fatherFirstName;
     private String fatherLastName;
     private String motherFirstName;
     private String motherLastName;
     private Date dob;
     private char gender;
     private String bloodGroup;
     private String firstLanguage;
     private String secondLanguage;
     private String thirdLanguage;
     private Date creationDate;
     private Date modifiedDate;
     private String dataSource;
     private String nationality;
     private String hospitalId;
     private Set userAccesses = new HashSet(0);

    public UserMaster() {
    }

	
    public UserMaster(String userId, ContactMaster contactMaster, AddressMaster addressMaster, String entityStatus, String firstName, String lastName, String fatherFirstName, String fatherLastName, String motherFirstName, String motherLastName, Date dob, char gender, String bloodGroup, String firstLanguage, String dataSource, String nationality) {
        this.userId = userId;
        this.contactMaster = contactMaster;
        this.addressMaster = addressMaster;
        this.entityStatus = entityStatus;
        this.firstName = firstName;
        this.lastName = lastName;
        this.fatherFirstName = fatherFirstName;
        this.fatherLastName = fatherLastName;
        this.motherFirstName = motherFirstName;
        this.motherLastName = motherLastName;
        this.dob = dob;
        this.gender = gender;
        this.bloodGroup = bloodGroup;
        this.firstLanguage = firstLanguage;
        this.dataSource = dataSource;
        this.nationality = nationality;
    }
    public UserMaster(String userId, UserAccess userAccessByCreatedBy, ContactMaster contactMaster, UserAccess userAccessByModifiedBy, AddressMaster addressMaster, String entityStatus, String firstName, String middleName, String lastName, String fatherFirstName, String fatherLastName, String motherFirstName, String motherLastName, Date dob, char gender, String bloodGroup, String firstLanguage, String secondLanguage, String thirdLanguage, Date creationDate, Date modifiedDate, String dataSource, String nationality, String hospitalId, Set userAccesses) {
       this.userId = userId;
       this.userAccessByCreatedBy = userAccessByCreatedBy;
       this.contactMaster = contactMaster;
       this.userAccessByModifiedBy = userAccessByModifiedBy;
       this.addressMaster = addressMaster;
       this.entityStatus = entityStatus;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.fatherFirstName = fatherFirstName;
       this.fatherLastName = fatherLastName;
       this.motherFirstName = motherFirstName;
       this.motherLastName = motherLastName;
       this.dob = dob;
       this.gender = gender;
       this.bloodGroup = bloodGroup;
       this.firstLanguage = firstLanguage;
       this.secondLanguage = secondLanguage;
       this.thirdLanguage = thirdLanguage;
       this.creationDate = creationDate;
       this.modifiedDate = modifiedDate;
       this.dataSource = dataSource;
       this.nationality = nationality;
       this.hospitalId = hospitalId;
       this.userAccesses = userAccesses;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public UserAccess getUserAccessByCreatedBy() {
        return this.userAccessByCreatedBy;
    }
    
    public void setUserAccessByCreatedBy(UserAccess userAccessByCreatedBy) {
        this.userAccessByCreatedBy = userAccessByCreatedBy;
    }
    public ContactMaster getContactMaster() {
        return this.contactMaster;
    }
    
    public void setContactMaster(ContactMaster contactMaster) {
        this.contactMaster = contactMaster;
    }
    public UserAccess getUserAccessByModifiedBy() {
        return this.userAccessByModifiedBy;
    }
    
    public void setUserAccessByModifiedBy(UserAccess userAccessByModifiedBy) {
        this.userAccessByModifiedBy = userAccessByModifiedBy;
    }
    public AddressMaster getAddressMaster() {
        return this.addressMaster;
    }
    
    public void setAddressMaster(AddressMaster addressMaster) {
        this.addressMaster = addressMaster;
    }
    public String getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(String entityStatus) {
        this.entityStatus = entityStatus;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFatherFirstName() {
        return this.fatherFirstName;
    }
    
    public void setFatherFirstName(String fatherFirstName) {
        this.fatherFirstName = fatherFirstName;
    }
    public String getFatherLastName() {
        return this.fatherLastName;
    }
    
    public void setFatherLastName(String fatherLastName) {
        this.fatherLastName = fatherLastName;
    }
    public String getMotherFirstName() {
        return this.motherFirstName;
    }
    
    public void setMotherFirstName(String motherFirstName) {
        this.motherFirstName = motherFirstName;
    }
    public String getMotherLastName() {
        return this.motherLastName;
    }
    
    public void setMotherLastName(String motherLastName) {
        this.motherLastName = motherLastName;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }
    public String getFirstLanguage() {
        return this.firstLanguage;
    }
    
    public void setFirstLanguage(String firstLanguage) {
        this.firstLanguage = firstLanguage;
    }
    public String getSecondLanguage() {
        return this.secondLanguage;
    }
    
    public void setSecondLanguage(String secondLanguage) {
        this.secondLanguage = secondLanguage;
    }
    public String getThirdLanguage() {
        return this.thirdLanguage;
    }
    
    public void setThirdLanguage(String thirdLanguage) {
        this.thirdLanguage = thirdLanguage;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getDataSource() {
        return this.dataSource;
    }
    
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId;
    }
    public Set getUserAccesses() {
        return this.userAccesses;
    }
    
    public void setUserAccesses(Set userAccesses) {
        this.userAccesses = userAccesses;
    }




}


